#include "point.h"

// Constructor
points::Point::Point(int X, int Y, points::Point *closestPoint)
{
    x = X;
    y = Y;
    nearestPoint = closestPoint;
}
// Destructor
points::Point::~Point()
{
    delete nearestPoint; //i guess
}

// Getters
int points::Point::getX()
{
    return x;
}

int points::Point::getY()
{
    return y;
}

points::Point *points::Point::getNearestPoint()
{
    return nearestPoint;
}

points::Point *points::Point::calcNearestPoint(Point *pointList[], unsigned long arrSize)
{
    float minDistance = 987654321; //set to arbitrarily high value, should probably not do this but i forgot how to do this better

    for (size_t i = 0; i < arrSize; i++) //size_t instead of unsigned long?
    {
        float arrayDistance = distPoints(*pointList[i]);

        if (arrayDistance < minDistance) 
        // if the minimum distance is more than the current distance produced from user vs. current array point:
        {
            minDistance = arrayDistance; //assign the minimum distance as the current array distance
            nearestPoint = new Point(pointList[i]->getX(), pointList[i]->getY(), pointList[i]->getNearestPoint()); 
            // take the x, y and getNearestPoint() argument and establishes "Point" Object on the heap
        }
    }

    return nearestPoint;
}

// Setters

void points::Point::setX(int newVal)
{
    x = newVal;
}

void points::Point::setY(int newVal)
{
    y = newVal;
}

void points::Point::setNearestPoint(Point *newNearestPoint)
{
    nearestPoint = newNearestPoint;
}

double points::Point::distPoints(Point &point)
{
    // distance = SQRT((x2-x1)^2 + (y2-y1)^2)
    //first coord set given by user, the other generated by an array

    return sqrt(pow((x - point.x), 2) + pow((y - point.y), 2)); 

    
}